version: 2
builds:
  - main: .
    binary: pmk
    goos: [linux]
    goarch: [amd64]
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -X main.BuildDate={{ .Date }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
