// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/001-prosemark-binder/US3-delete-node.txt

package acceptance_test

import (
	"testing"
)

// Deleting a leaf chapter removes its entry from the binder.
// Source: specs/001-prosemark-binder/US3-delete-node.txt:2
func Test_Deleting_a_leaf_chapter_removes_its_entry_from_the_binder(t *testing.T) {
	// GIVEN a binder with a chapter that has no sub-chapters.
	// WHEN the author deletes that chapter.
	// THEN the chapter entry is removed from the binder.

	t.Skip("acceptance test not yet bound")
}

// Deleting a chapter also removes all of its nested sub-chapters.
// Source: specs/001-prosemark-binder/US3-delete-node.txt:11
func Test_Deleting_a_chapter_also_removes_all_of_its_nested_sub_chapters(t *testing.T) {
	// GIVEN a binder with a chapter that contains nested sub-chapters.
	// WHEN the author deletes the parent chapter.
	// THEN the parent chapter and all its sub-chapters are removed.

	t.Skip("acceptance test not yet bound")
}

// Deleting the only entry inside a nested section prunes the now-empty section.
// Source: specs/001-prosemark-binder/US3-delete-node.txt:20
func Test_Deleting_the_only_entry_inside_a_nested_section_prunes_the_now_empty_section(t *testing.T) {
	// GIVEN a binder with a nested section containing only one sub-chapter.
	// WHEN the author deletes that sub-chapter.
	// THEN the now-empty nested section is also removed.
	// THEN an "empty section removed" warning is included in the result.

	t.Skip("acceptance test not yet bound")
}

// Consecutive blank lines created by a deletion are collapsed into one.
// Source: specs/001-prosemark-binder/US3-delete-node.txt:30
func Test_Consecutive_blank_lines_created_by_a_deletion_are_collapsed_into_one(t *testing.T) {
	// GIVEN a binder where deleting a chapter would leave two blank lines in a row.
	// WHEN the author deletes that chapter.
	// THEN the two consecutive blank lines are collapsed into one.

	t.Skip("acceptance test not yet bound")
}

// Deleting a chapter with non-structural text removes that text too, with a warning.
// Source: specs/001-prosemark-binder/US3-delete-node.txt:39
func Test_Deleting_a_chapter_with_non_structural_text_removes_that_text_too_with_a_warning(t *testing.T) {
	// GIVEN a binder with a chapter entry that has additional descriptive text after the chapter link.
	// WHEN the author deletes that chapter.
	// THEN the entry and its additional text are both removed.
	// THEN a "non-structural content destroyed" warning is included in the result.

	t.Skip("acceptance test not yet bound")
}

// Attempting to delete a non-existent chapter returns an error without modifying the binder.
// Source: specs/001-prosemark-binder/US3-delete-node.txt:49
func Test_Attempting_to_delete_a_non_existent_chapter_returns_an_error_without_modifying_the_binder(t *testing.T) {
	// GIVEN a selector that does not match any chapter in the binder.
	// WHEN the author tries to delete using that selector.
	// THEN a "not found" error is returned.
	// THEN the binder is unchanged.

	t.Skip("acceptance test not yet bound")
}

// Deleting a chapter that uses footnote-style links preserves the link definition in the file.
// Source: specs/001-prosemark-binder/US3-delete-node.txt:59
func Test_Deleting_a_chapter_that_uses_footnote_style_links_preserves_the_link_definition_in_the_file(t *testing.T) {
	// GIVEN a binder with a chapter that uses a footnote-style link, with the definition stored at the bottom of the file.
	// WHEN the author deletes that chapter.
	// THEN the chapter entry is removed.
	// THEN the footnote link definition at the bottom of the file is kept intact.

	t.Skip("acceptance test not yet bound")
}

// Deleting the last top-level chapter removes any trailing blank lines from the file.
// Source: specs/001-prosemark-binder/US3-delete-node.txt:69
func Test_Deleting_the_last_top_level_chapter_removes_any_trailing_blank_lines_from_the_file(t *testing.T) {
	// GIVEN a binder with only one top-level chapter.
	// WHEN the author deletes that chapter.
	// THEN any blank lines remaining at the end of the file are removed.

	t.Skip("acceptance test not yet bound")
}
