// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt

package acceptance_test

import (
	"testing"
)

// New chapter is appended after all existing chapters by default.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:2
func Test_New_chapter_is_appended_after_all_existing_chapters_by_default(t *testing.T) {
	// GIVEN a binder with one existing top-level chapter.
	// WHEN the author adds a new chapter at the top level using default placement.
	// THEN the new chapter appears after the existing chapter.

	t.Skip("acceptance test not yet bound")
}

// New chapter is inserted before all existing chapters when first position is requested.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:11
func Test_New_chapter_is_inserted_before_all_existing_chapters_when_first_position_is_requested(t *testing.T) {
	// GIVEN a binder with several top-level chapters.
	// WHEN the author adds a new chapter at the first position.
	// THEN the new chapter appears before all existing chapters.

	t.Skip("acceptance test not yet bound")
}

// New chapter is inserted at a specific numbered position.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:20
func Test_New_chapter_is_inserted_at_a_specific_numbered_position(t *testing.T) {
	// GIVEN a binder with several top-level chapters.
	// WHEN the author adds a new chapter at position one, counting from zero.
	// THEN the new chapter appears at position one in the list.

	t.Skip("acceptance test not yet bound")
}

// New chapter is inserted before a named sibling.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:29
func Test_New_chapter_is_inserted_before_a_named_sibling(t *testing.T) {
	// GIVEN a binder with chapters named "A", "B", and "C".
	// WHEN the author adds a new chapter before "B".
	// THEN the new chapter appears between "A" and "B".

	t.Skip("acceptance test not yet bound")
}

// Adding a chapter that already exists in the same parent is skipped with a warning.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:38
func Test_Adding_a_chapter_that_already_exists_in_the_same_parent_is_skipped_with_a_warning(t *testing.T) {
	// GIVEN a binder where the new chapter's file is already listed under the target parent.
	// WHEN the author adds the chapter again without the force option.
	// THEN the binder is unchanged.
	// THEN a "duplicate skipped" warning is included in the result.

	t.Skip("acceptance test not yet bound")
}

// Adding a duplicate chapter with the force option inserts a second copy.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:48
func Test_Adding_a_duplicate_chapter_with_the_force_option_inserts_a_second_copy(t *testing.T) {
	// GIVEN a binder where the new chapter's file is already listed under the target parent.
	// WHEN the author adds the chapter again with the force option.
	// THEN the binder now contains two entries for that chapter file.

	t.Skip("acceptance test not yet bound")
}

// New chapter inherits the numbered list style of its siblings.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:57
func Test_New_chapter_inherits_the_numbered_list_style_of_its_siblings(t *testing.T) {
	// GIVEN a binder where existing chapters are arranged in a numbered list with period markers.
	// WHEN the author adds a new chapter.
	// THEN the new chapter uses the next sequential number with the same period marker style.

	t.Skip("acceptance test not yet bound")
}

// New chapter inherits the tab indentation of its siblings.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:66
func Test_New_chapter_inherits_the_tab_indentation_of_its_siblings(t *testing.T) {
	// GIVEN a binder where existing nested chapters are indented with tabs.
	// WHEN the author adds a new nested chapter.
	// THEN the new chapter is indented with tabs to match its siblings.

	t.Skip("acceptance test not yet bound")
}

// A chapter title containing square bracket characters is stored with those characters escaped.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:75
func Test_A_chapter_title_containing_square_bracket_characters_is_stored_with_those_characters_escaped(t *testing.T) {
	// GIVEN the author wants to add a chapter whose title contains square bracket characters.
	// WHEN the chapter is added to the binder.
	// THEN the stored title has those square bracket characters properly escaped.

	t.Skip("acceptance test not yet bound")
}

// Attempting to add a chapter to a non-existent parent returns an error.
// Source: specs/001-prosemark-binder/US2-add-child-node.txt:84
func Test_Attempting_to_add_a_chapter_to_a_non_existent_parent_returns_an_error(t *testing.T) {
	// GIVEN a selector that does not match any node in the binder.
	// WHEN the author tries to add a chapter under that selector as parent.
	// THEN a "not found" error is returned.
	// THEN the binder is unchanged.

	t.Skip("acceptance test not yet bound")
}
