// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/001-prosemark-binder/US4-move-node.txt

package acceptance_test

import (
	"testing"
)

// Moving a chapter to a different position reorders the binder.
// Source: specs/001-prosemark-binder/US4-move-node.txt:2
func Test_Moving_a_chapter_to_a_different_position_reorders_the_binder(t *testing.T) {
	// GIVEN a binder with two sibling chapters in a certain order.
	// WHEN the author moves one chapter to the other's position.
	// THEN the chapters appear in the new order.

	t.Skip("acceptance test not yet bound")
}

// Moving a chapter moves its entire sub-chapter tree with it.
// Source: specs/001-prosemark-binder/US4-move-node.txt:11
func Test_Moving_a_chapter_moves_its_entire_sub_chapter_tree_with_it(t *testing.T) {
	// GIVEN a binder with a chapter that has nested sub-chapters.
	// WHEN the author moves that chapter to a different location.
	// THEN the chapter and all its sub-chapters appear together at the destination.

	t.Skip("acceptance test not yet bound")
}

// Moving a chapter into one of its own descendants is rejected.
// Source: specs/001-prosemark-binder/US4-move-node.txt:20
func Test_Moving_a_chapter_into_one_of_its_own_descendants_is_rejected(t *testing.T) {
	// GIVEN a binder where chapter "A" contains chapter "B".
	// WHEN the author tries to move "A" to be under "B".
	// THEN a "circular move" error is returned.
	// THEN the binder is unchanged.

	t.Skip("acceptance test not yet bound")
}

// Moving a chapter that uses footnote-style links preserves its link format.
// Source: specs/001-prosemark-binder/US4-move-node.txt:30
func Test_Moving_a_chapter_that_uses_footnote_style_links_preserves_its_link_format(t *testing.T) {
	// GIVEN a binder with a chapter that uses a footnote-style link.
	// WHEN the author moves that chapter to a different location.
	// THEN the moved chapter still uses its footnote-style link at the new location.

	t.Skip("acceptance test not yet bound")
}

// Moving a chapter with a tooltip preserves the tooltip text.
// Source: specs/001-prosemark-binder/US4-move-node.txt:39
func Test_Moving_a_chapter_with_a_tooltip_preserves_the_tooltip_text(t *testing.T) {
	// GIVEN a binder with a chapter whose link has a tooltip.
	// WHEN the author moves that chapter to a different location.
	// THEN the moved chapter's link still has the tooltip text at the new location.

	t.Skip("acceptance test not yet bound")
}

// Moved chapter uses the indentation style of its new sibling group.
// Source: specs/001-prosemark-binder/US4-move-node.txt:48
func Test_Moved_chapter_uses_the_indentation_style_of_its_new_sibling_group(t *testing.T) {
	// GIVEN a binder where the destination section uses a different indentation style than the source section.
	// WHEN the author moves a chapter to the destination section.
	// THEN the moved chapter uses the destination section's indentation style.

	t.Skip("acceptance test not yet bound")
}

// Moving a chapter with non-structural text destroys that text with a warning.
// Source: specs/001-prosemark-binder/US4-move-node.txt:57
func Test_Moving_a_chapter_with_non_structural_text_destroys_that_text_with_a_warning(t *testing.T) {
	// GIVEN a binder with a chapter entry that has additional descriptive text after its link.
	// WHEN the author moves that chapter.
	// THEN the chapter appears at the destination without the additional text.
	// THEN a "non-structural content destroyed" warning is included in the result.

	t.Skip("acceptance test not yet bound")
}
