// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/002-node-identity/US3-edit-node.txt

package acceptance_test

import (
	"testing"
)

// Editing a node opens the draft file and refreshes the last-edited timestamp on save.
// Source: specs/002-node-identity/US3-edit-node.txt:2
func Test_Editing_a_node_opens_the_draft_file_and_refreshes_the_last_edited_timestamp_on_save(t *testing.T) {
	// GIVEN a node registered in the project outline with a corresponding draft file.
	// GIVEN a preferred editor is configured.
	// WHEN the author edits the node's draft.
	// THEN the preferred editor opens the node's draft file.
	// THEN the node's last-edited timestamp is updated to the current time when the editor closes.

	t.Skip("acceptance test not yet bound")
}

// Editing the notes part of a node refreshes the draft's last-edited timestamp.
// Source: specs/002-node-identity/US3-edit-node.txt:13
func Test_Editing_the_notes_part_of_a_node_refreshes_the_draft_s_last_edited_timestamp(t *testing.T) {
	// GIVEN a node registered in the project outline with a corresponding draft file and a notes file.
	// GIVEN a preferred editor is configured.
	// WHEN the author edits the node's notes.
	// THEN the preferred editor opens the node's notes file.
	// THEN the draft file's last-edited timestamp is updated to the current time when the editor closes.

	t.Skip("acceptance test not yet bound")
}

// Editing the notes part creates the notes file when it does not yet exist.
// Source: specs/002-node-identity/US3-edit-node.txt:24
func Test_Editing_the_notes_part_creates_the_notes_file_when_it_does_not_yet_exist(t *testing.T) {
	// GIVEN a node registered in the project outline with a draft file but no notes file.
	// GIVEN a preferred editor is configured.
	// WHEN the author edits the node's notes.
	// THEN a new empty notes file is created for the node.
	// THEN the preferred editor opens the new notes file.

	t.Skip("acceptance test not yet bound")
}

// Editing a node that is not registered in the outline fails with a clear error.
// Source: specs/002-node-identity/US3-edit-node.txt:35
func Test_Editing_a_node_that_is_not_registered_in_the_outline_fails_with_a_clear_error(t *testing.T) {
	// GIVEN an initialized project.
	// WHEN the author attempts to edit a node that is not registered in the project outline.
	// THEN the command fails with an error indicating the node is not in the outline.

	t.Skip("acceptance test not yet bound")
}

// Editing a node whose file is missing fails with a clear error.
// Source: specs/002-node-identity/US3-edit-node.txt:44
func Test_Editing_a_node_whose_file_is_missing_fails_with_a_clear_error(t *testing.T) {
	// GIVEN a node registered in the project outline but whose draft file does not exist on disk.
	// WHEN the author attempts to edit the node's draft.
	// THEN the command fails with an error indicating the node file is missing.

	t.Skip("acceptance test not yet bound")
}

// Editing a node without specifying a part defaults to the draft.
// Source: specs/002-node-identity/US3-edit-node.txt:53
func Test_Editing_a_node_without_specifying_a_part_defaults_to_the_draft(t *testing.T) {
	// GIVEN a node registered in the project outline with a draft file.
	// GIVEN a preferred editor is configured.
	// WHEN the author edits the node without specifying which part to open.
	// THEN the preferred editor opens the node's draft file.

	t.Skip("acceptance test not yet bound")
}

// Editing a node fails immediately when no preferred editor is configured.
// Source: specs/002-node-identity/US3-edit-node.txt:63
func Test_Editing_a_node_fails_immediately_when_no_preferred_editor_is_configured(t *testing.T) {
	// GIVEN a node registered in the project outline with a draft file.
	// GIVEN no preferred editor is configured.
	// WHEN the author attempts to edit the node.
	// THEN the command fails with an error indicating no preferred editor is configured.
	// THEN no file is created or modified.

	t.Skip("acceptance test not yet bound")
}
