// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/002-node-identity/US1-init-project.txt

package acceptance_test

import (
	"testing"
)

// An empty directory becomes a prosemark project after initialization.
// Source: specs/002-node-identity/US1-init-project.txt:2
func Test_An_empty_directory_becomes_a_prosemark_project_after_initialization(t *testing.T) {
	// GIVEN a directory with no prosemark project files.
	// WHEN the author initializes the project.
	// THEN a project outline file is created with the managed outline block.
	// THEN a project settings file is created with default settings.

	t.Skip("acceptance test not yet bound")
}

// Initialization refuses to overwrite an existing project without explicit permission.
// Source: specs/002-node-identity/US1-init-project.txt:12
func Test_Initialization_refuses_to_overwrite_an_existing_project_without_explicit_permission(t *testing.T) {
	// GIVEN a directory where a project outline file already exists with author content.
	// WHEN the author initializes the project without the force option.
	// THEN the command fails with an informative error message.
	// THEN the existing outline file is unchanged.

	t.Skip("acceptance test not yet bound")
}

// Forced reinitialization recreates project files with defaults.
// Source: specs/002-node-identity/US1-init-project.txt:22
func Test_Forced_reinitialization_recreates_project_files_with_defaults(t *testing.T) {
	// GIVEN a directory that has already been initialized as a prosemark project.
	// WHEN the author re-initializes the project with the force option.
	// THEN the managed outline block is confirmed present in the project outline.
	// THEN the project settings file is overwritten with default settings.

	t.Skip("acceptance test not yet bound")
}

// Initialization creates only the missing project file when settings already exist.
// Source: specs/002-node-identity/US1-init-project.txt:32
func Test_Initialization_creates_only_the_missing_project_file_when_settings_already_exist(t *testing.T) {
	// GIVEN a directory where a project settings file exists but no project outline file.
	// WHEN the author initializes the project.
	// THEN the project outline file is created.
	// THEN the existing project settings file is left unchanged.

	t.Skip("acceptance test not yet bound")
}

// Initialization fails cleanly when the directory is not writable.
// Source: specs/002-node-identity/US1-init-project.txt:42
func Test_Initialization_fails_cleanly_when_the_directory_is_not_writable(t *testing.T) {
	// GIVEN a directory where the author does not have write permission.
	// WHEN the author initializes the project.
	// THEN the command fails with a clear filesystem error.
	// THEN no partial project files are left behind.

	t.Skip("acceptance test not yet bound")
}
