// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/003-placeholder-parsing/US2-placeholder-nodes-with-children.txt

package acceptance_test

import (
	"fmt"
	"strings"
	"testing"
)

// A placeholder parent can contain a file-backed child node.
// Source: specs/003-placeholder-parsing/US2-placeholder-nodes-with-children.txt:2
func Test_A_placeholder_parent_can_contain_a_file_backed_child_node(t *testing.T) {
	// GIVEN a binder file with a placeholder item that has an indented file-backed child.
	dir := t.TempDir()
	writeFile(t, dir, "_binder.md",
		"<!-- prosemark-binder:v1 -->\n- [Part I]()\n  - [chapter-one.md](chapter-one.md \"Chapter One\")\n")
	writeFile(t, dir, "chapter-one.md", "")

	// WHEN the binder is parsed.
	result := runParse(t, dir+"/_binder.md")
	if !result.OK {
		t.Fatalf("expected exit 0\nstdout: %s\nstderr: %s", result.Stdout, result.Stderr)
	}

	// THEN the parse result contains a placeholder parent node.
	if !strings.Contains(result.Stdout, `"title":"Part I"`) {
		t.Errorf("expected placeholder parent node, got: %s", result.Stdout)
	}

	// THEN the parent node has one child with a non-empty file path.
	if !strings.Contains(result.Stdout, `"target":"chapter-one.md"`) {
		t.Errorf("expected child node with target, got: %s", result.Stdout)
	}
}

// Placeholder nodes can be nested three levels deep.
// Source: specs/003-placeholder-parsing/US2-placeholder-nodes-with-children.txt:12
func Test_Placeholder_nodes_can_be_nested_three_levels_deep(t *testing.T) {
	// GIVEN a binder file with placeholder nodes nested three levels deep.
	dir := t.TempDir()
	writeFile(t, dir, "_binder.md",
		"<!-- prosemark-binder:v1 -->\n- [Level 1]()\n  - [Level 2]()\n    - [Level 3]()\n")

	// WHEN the binder is parsed.
	result := runParse(t, dir+"/_binder.md")
	if !result.OK {
		t.Fatalf("expected exit 0\nstdout: %s\nstderr: %s", result.Stdout, result.Stderr)
	}

	// THEN each placeholder node appears at the correct depth in the outline.
	for _, title := range []string{"Level 1", "Level 2", "Level 3"} {
		if !strings.Contains(result.Stdout, fmt.Sprintf(`"title":%q`, title)) {
			t.Errorf("expected node %q in output, got: %s", title, result.Stdout)
		}
	}
}
