// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/003-placeholder-parsing/US4-no-spurious-diagnostics.txt

package acceptance_test

import (
	"testing"
)

// A placeholder node does not trigger a missing-file diagnostic.
// Source: specs/003-placeholder-parsing/US4-no-spurious-diagnostics.txt:2
func Test_A_placeholder_node_does_not_trigger_a_missing_file_diagnostic(t *testing.T) {
	// GIVEN a binder file with a placeholder item in a project with known files.
	// WHEN the binder is parsed.
	// THEN no missing-file diagnostic is emitted for the placeholder node.

	t.Skip("acceptance test not yet bound")
}

// Two identical placeholder items do not trigger a duplicate diagnostic.
// Source: specs/003-placeholder-parsing/US4-no-spurious-diagnostics.txt:11
func Test_Two_identical_placeholder_items_do_not_trigger_a_duplicate_diagnostic(t *testing.T) {
	// GIVEN a binder file with two placeholder items that share the same title.
	// WHEN the binder is parsed.
	// THEN no duplicate-reference diagnostic is emitted.

	t.Skip("acceptance test not yet bound")
}
