// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/003-placeholder-parsing/US2-placeholder-nodes-with-children.txt

package acceptance_test

import (
	"testing"
)

// A placeholder parent can contain a file-backed child node.
// Source: specs/003-placeholder-parsing/US2-placeholder-nodes-with-children.txt:2
func Test_A_placeholder_parent_can_contain_a_file_backed_child_node(t *testing.T) {
	// GIVEN a binder file with a placeholder item that has an indented file-backed child.
	// WHEN the binder is parsed.
	// THEN the parse result contains a placeholder parent node.
	// THEN the parent node has one child with a non-empty file path.

	t.Skip("acceptance test not yet bound")
}

// Placeholder nodes can be nested three levels deep.
// Source: specs/003-placeholder-parsing/US2-placeholder-nodes-with-children.txt:12
func Test_Placeholder_nodes_can_be_nested_three_levels_deep(t *testing.T) {
	// GIVEN a binder file with placeholder nodes nested three levels deep.
	// WHEN the binder is parsed.
	// THEN each placeholder node appears at the correct depth in the outline.

	t.Skip("acceptance test not yet bound")
}
