// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/003-placeholder-parsing/US1-recognize-placeholder-nodes.txt

package acceptance_test

import (
	"strings"
	"testing"
)

// A placeholder item [Chapter 3]() becomes a node in the outline tree.
// Source: specs/003-placeholder-parsing/US1-recognize-placeholder-nodes.txt:2
func Test_A_placeholder_item_Chapter_3_becomes_a_node_in_the_outline_tree(t *testing.T) {
	// GIVEN a binder file with a single placeholder list item.
	dir := t.TempDir()
	writeFile(t, dir, "_binder.md", "<!-- prosemark-binder:v1 -->\n- [Chapter 3]()\n")

	// WHEN the binder is parsed.
	result := runParse(t, dir+"/_binder.md")
	if !result.OK {
		t.Fatalf("expected exit 0\nstdout: %s\nstderr: %s", result.Stdout, result.Stderr)
	}

	// THEN the parse result contains a node with the placeholder title.
	if !strings.Contains(result.Stdout, `"title":"Chapter 3"`) {
		t.Errorf("expected node with title 'Chapter 3', got: %s", result.Stdout)
	}

	// THEN the node has no associated file path.
	if strings.Contains(result.Stdout, `"target"`) {
		t.Errorf("expected no target field for placeholder, got: %s", result.Stdout)
	}

	// THEN no diagnostic is emitted.
	if !strings.Contains(result.Stdout, `"diagnostics":[]`) {
		t.Errorf("expected no diagnostics, got: %s", result.Stdout)
	}
}

// A bare placeholder []() with no title parses without error.
// Source: specs/003-placeholder-parsing/US1-recognize-placeholder-nodes.txt:13
func Test_A_bare_placeholder_with_no_title_parses_without_error(t *testing.T) {
	// GIVEN a binder file with a placeholder item that has no title text.
	dir := t.TempDir()
	writeFile(t, dir, "_binder.md", "<!-- prosemark-binder:v1 -->\n- []()\n")

	// WHEN the binder is parsed.
	result := runParse(t, dir+"/_binder.md")
	if !result.OK {
		t.Fatalf("expected exit 0\nstdout: %s\nstderr: %s", result.Stdout, result.Stderr)
	}

	// THEN the parse result contains a node with an empty title.
	if !strings.Contains(result.Stdout, `"type":"node"`) {
		t.Errorf("expected a placeholder node, got: %s", result.Stdout)
	}

	// THEN the node has no associated file path.
	if strings.Contains(result.Stdout, `"target"`) {
		t.Errorf("expected no target field, got: %s", result.Stdout)
	}

	// THEN no diagnostic is emitted.
	if !strings.Contains(result.Stdout, `"diagnostics":[]`) {
		t.Errorf("expected no diagnostics, got: %s", result.Stdout)
	}
}

// Multiple identical placeholder items each appear as a distinct node.
// Source: specs/003-placeholder-parsing/US1-recognize-placeholder-nodes.txt:24
func Test_Multiple_identical_placeholder_items_each_appear_as_a_distinct_node(t *testing.T) {
	// GIVEN a binder file with two placeholder items sharing the same title.
	dir := t.TempDir()
	writeFile(t, dir, "_binder.md",
		"<!-- prosemark-binder:v1 -->\n- [Chapter]()\n- [Chapter]()\n")

	// WHEN the binder is parsed.
	result := runParse(t, dir+"/_binder.md")
	if !result.OK {
		t.Fatalf("expected exit 0\nstdout: %s\nstderr: %s", result.Stdout, result.Stderr)
	}

	// THEN the parse result contains two distinct nodes.
	if count := strings.Count(result.Stdout, `"title":"Chapter"`); count != 2 {
		t.Errorf("expected 2 nodes with title 'Chapter', got %d: %s", count, result.Stdout)
	}

	// THEN no duplicate-reference diagnostic is emitted.
	if !strings.Contains(result.Stdout, `"diagnostics":[]`) {
		t.Errorf("expected no diagnostics (no BNDW003), got: %s", result.Stdout)
	}
}
