// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/003-placeholder-parsing/US3-placeholder-round-trip.txt

package acceptance_test

import (
	"testing"
)

// A binder with placeholder items serializes identically to its input.
// Source: specs/003-placeholder-parsing/US3-placeholder-round-trip.txt:2
func Test_A_binder_with_placeholder_items_serializes_identically_to_its_input(t *testing.T) {
	// GIVEN a binder file containing placeholder items at various nesting levels.
	// WHEN the file is parsed and then written back to text.
	// THEN the output is byte-for-byte identical to the original input.

	// Delegates to the conformance ParseStability suite for fixture dirs 121–125.
	result := runConformance(t, "TestConformance_ParseStability/12")
	if !result.OK {
		t.Fatalf("round-trip stability failed for placeholder fixtures\nstdout: %s\nstderr: %s",
			result.Stdout, result.Stderr)
	}
}
